### ISSUE TITLE
Package Install error

### ISSUE THREAD

**Issue by TouseefXMobile** [mjishnu/alt-app-installer-cli#1]
Installing Packages...
Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "install.py", line 19, in install
  File "install.py", line 8, in run
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[1684] Failed to execute script 'main' due to unhandled exception!

(also used the pyinstaller verison of alt app installer but it just gives me error when opened)

**Comment by TouseefXMobile** [comment]
also i am doing this on windows pe in a hard drive failure PC

**Comment by mjishnu** [comment]
from the trace back you provided it seems like, we are not able to access the downloaded files or powershell (not clear). if the files are downloaded try manually installing the app using app installer or using the powershell command `Add-AppPackage [enter file path here]`. for more info i want the log.txt file it should be in the folder where you ran the script (or .exe file if using alt app installer cli.exe)

**Comment by mjishnu** [comment]
then you should try using app installer sometime it would be pre-installed if you also lack it try to install powershell if that also not possible idk what to do since you need some mechanism in the os to install apps tho some apps you can extract the appx and run but some wont work.
